server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ikplusdb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  ikplus:
    jwt:
      secret-key: "RS9]=_GH#L8(#xyl~D=kmJ'kP-2U^dOD+Y[6nYZRm2-5~U,vTs"
      issuer: "IKPLUS_JWT_ISSUER"